### ISSUE TITLE
How do I produce coverage data with this tool?

### ISSUE THREAD

**Issue by chenop** [invertase/bridge#29]
Thanks for creating this library - looks interesting.
I cannot understand from the README.md how should I invoke coverage.
Currently running test with detox:
`npx detox test --configuration ios.debug`

What should I do in order to create the coverage for the test Im running?

**Comment by mikehardy** [comment]
That depends on what you want. The main consumer of this module is react-native-firebase, I encourage you to look at the e2e testing app in the tests directory there along with the main package.json and tests/package.json to see how coverage could work.

As with all things coverage-related in javascript it boils down to "make sure you instrument the code before you run it" (using istanbul), "make sure you get the coverage data after you run it" (however that works for you...)

Similar to mocking in jest, there are all sorts of ways to do it, but react-native-firebase may serve as one example
